### ISSUE TITLE
safely shutting down

### ISSUE THREAD

**Issue by pathsny** [propublica/daybreak#31]
Hi, I'm using Daybreak with sinatara, and since Sinatra does not have its own exit hook, I've used an at_exit block to flush the database and close it before the application ends. However, this results in a strange error at times

`closing database
/Users/vsi/.rvm/gems/ruby-2.1.5/gems/daybreak-0.3.0/lib/daybreak/queue/mri.rb:49:in `stop': stopping only thread (ThreadError)
    note: use sleep to stop forever
    from /Users/vsi/.rvm/gems/ruby-2.1.5/gems/daybreak-0.3.0/lib/daybreak/queue/mri.rb:49:in `flush'
    from /Users/vsi/.rvm/gems/ruby-2.1.5/gems/daybreak-0.3.0/lib/daybreak/db.rb:183:in `flush'
    from /Users/vsi/Projects/anidb-ruby/web/lib/models.rb:29:in `close'
    from /Users/vsi/Projects/anidb-ruby/web/lib/models.rb:77:in `block in <top (required)>'`

Is there a better way to do this?

**Comment by thejefflarson** [comment]
@minad can you take a look? It's in your mri optimization, I wonder if something changed post 2.0, here's the documentation on it:

http://ruby-doc.org/core-2.2.0/ThreadError.html

@pathsny because this only happens when the write queue is empty, all of the data should be flushed already before the exit. It's probably a less scary error than it looks like.

**Comment by minad** [comment]
we already have an at_exit handler. Why do you need another one?

**Comment by thejefflarson** [comment]
Oh I see, I bet this warning is the problem: 

https://github.com/propublica/daybreak/blob/master/lib/daybreak/db.rb#L262

In reality our exit handler will do what @pathsny's exit handler is doing. Maybe we should clarify the warning a bit?

**Comment by minad** [comment]
I think this is what we are doing already?

**Comment by pathsny** [comment]
oh yep. I had seen the warning and hadn't looked at the source. So it looks like I do not need an exit handler. 

The warning definetly gave me the wrong impression. Do you not also need to flush before closing though?

**Comment by thejefflarson** [comment]
@minad's right the journal will wait until it has the worker has finished it's current work to close. https://github.com/propublica/daybreak/blob/master/lib/daybreak/journal.rb#L25

Any suggestions on updated language? Or should we kill the warning?

**Comment by pathsny** [comment]
If all writes and being flushed and the database is being closed, then it seems pretty safe to kill the warning. It looks like you arent really expecting clients to have to remember to do these actions.

**Comment by thejefflarson** [comment]
@minad safe to kill it?

**Comment by minad** [comment]
No, we should keep the warning. The library user should ensure that the db is closed properly.

**Comment by pathsny** [comment]
@minad using this with sinatra, the best way todo this is via an on_exit handler. So I'm not sure what you're expecting the library user to do here.

**Comment by minad** [comment]
The problem is that the order of the exit handlers is not determined and daybreak uses its own exit handler to ensure that all dbs are closed. We have to keep the warning for the cases where people forget to close the db. We could remove the warning or offer an option to disable it.

**Comment by burningTyger** [comment]
ok, works perfectly. For those who don't know how to use this:

    db = Daybreak::DB.new "file.db"                                                                                                                                                                      
    at_exit {db.close}

Wherever you open your DB, add an `at_exit`
